engine/data/score-data-api/src/main/java/io/cloudslang/engine/dialects/ScoreDialectResolver.java
Fixes CloudSlang/cloud-slang#242
Signed-off-by: Meir Wahnon <meir.wahnon@hp.com>
=> Replacing System.out.print with logger ("Database name is: "...)

engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/ScoreTriggeringImpl.java, score-api/src/main/java/io/cloudslang/score/api/TriggeringProperties.java, score-api/src/main/java/io/cloudslang/score/api/execution/ExecutionMetadataConsts.java, worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java, worker/worker-execution/score-worker-execution-impl/src/test/java/io/cloudslang/worker/execution/services/ExecutionServiceTest.java
fix cloudslang/cloud-slang#340
The score engine will replace the execution plan name & id values on the ExecutionRuntimeServices metadata map when replacing the execution plan
=> Update metadata during running execution plan change

package/score-worker/src/main/java/io/cloudslang/schema/ConfValue.java
Now config values like numberOfExecutionThreads, inBufferCapacity can be provided as system properties cloudslang.worker.numberOfExecutionThreads, cloudslang.worker.inBufferCapacity
=> Load config value from Java system properties first, then from the xml

worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/InBuffer.java
The defect described flows that are executed in delay, this was caused by a false triggering of the defense mechanism in the InBuffer that does not pull new messages when there are less than 50Mb of free memory, however this mechanism does not take into account GC, and the amount of memory that can be released as a result of GC
=> This commit will fix defect 28687

engine/data/score-data-api/src/main/resources/META-INF/database/score.changes.xml, engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/entities/Worker.java, engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/entities/WorkerNode.java, engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/services/WorkerNodeService.java, engine/node/score-node-impl/src/main/java/io/cloudslang/engine/node/services/WorkerNodeServiceImpl.java, engine/node/score-node-impl/src/test/java/io/cloudslang/engine/node/services/WorkerNodeServiceTest.java, package/score-all/src/main/java/io/cloudslang/schema/EngineBeanDefinitionParser.java, score-api/src/main/resources/io/cloudslang/schema/score.xsd
Signed-off-by: Natasha Beck <natasha.kravtsov@hp.com>
In order to support worker in cluster we need to have version for each worker.
In order to have correct execution all workers should have the same version.
=> Worker version support

engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/CancelExecutionServiceImpl.java, engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/CancelExecutionServiceTest.java
Signed-off-by: Hajyhia Shehab shehab.hajyhia@hpe.com
Covering the status pending-pause by Cancel action will solve the cases were execution stack on pending-pause therefore, timeout will handle such executions and prevent them to be stacked for ever
=> Cover Canceling by interrupt execution with status pending-pause

worker/worker-manager/score-worker-manager-api/src/main/java/io/cloudslang/worker/management/services/WorkerMonitorInfoEnum.java, worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/monitor/ScheduledWorkerLoadMonitor.java, worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/monitor/WorkerMonitorsImpl.java, worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/monitor/ScheduledWorkerLoadMonitorTest.java, worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/monitor/WorkerMonitorsImplTest.java
fixes #79 
This is a solution for the defect: WorkerExecutionMonitorServiceImpl messages contain several typos #79
=> Correct the typos in the WorkerMonitorInfoEnum

engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/services/BusyWorkersService.java, engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepository.java, engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryImpl.java, engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/BusyWorkersServiceImpl.java, engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/ExecutionQueueServiceImpl.java, engine/queue/score-queue-impl/src/test/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryTest.java, engine/queue/score-queue-impl/src/test/java/io/cloudslang/engine/queue/services/BusyWorkersServiceTest.java, engine/queue/score-queue-impl/src/test/java/io/cloudslang/engine/queue/services/ExecutionQueueServiceTest.java, engine/queue/score-queue-impl/src/test/java/io/cloudslang/engine/queue/services/QueueDispatcherServiceTest.java, engine/queue/score-queue-impl/src/test/java/io/cloudslang/engine/queue/services/cleaner/QueueCleanerServiceTest.java, package/score-all/src/main/java/io/cloudslang/schema/EngineBeanDefinitionParser.java, package/score-all/src/main/resources/META-INF/spring/score/context/scoreEngineSchedulerContext.xml, score-tests/src/test/java/io/cloudslang/schema/EngineTest.java
Added busyWorkersService that eliminates redundant DB requests from central
when  workers that do not have work poll the central for work
Signed-off by: Doron Sekler doron.sekler@hpe.com
=> Added busyWorkersService that eliminates redundant DB requests from central

runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/java/JavaExecutor.java
fixes CloudSlang/cloud-slang#719
current thread should use same classloader as classloader resolved for action as some third-parties can use it to resolve classes
=> current thread should use same classloader as classloader resolved for dependencies

worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerManager.java
`addExecution `can be called from multiple threads at the same time
`endExecution  `can be called from multiple threads at the same time
`addExecution`/`endExecution `can be called from multiple threads at the same time
There are some multithreading issues in the original code which should be fixed in the new code
=> Fix multi threading issue with addExecution endExecution

engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryImpl.java, engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/StatementAwareJdbcTemplateWrapper.java
`JdbcTemplate` is thread safe only once configured.
We reconfigured the JDBC template for select queries to provide statement batch sizes.
This pull request fixes the thread safety in case of reconfiguration through `io.cloudslang.engine.queue.services.StatementAwareJdbcTemplateWrapper`
=> Fix thread safety for JDBC template in case of reconfiguration of statement size

worker/worker-execution/score-worker-execution-api/src/main/java/io/cloudslang/worker/execution/services/ExecutionService.java, worker/worker-execution/score-worker-execution-api/src/main/java/io/cloudslang/worker/execution/services/ExternalExecutionService.java, worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java, worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExternalExecutionServiceImpl.java, worker/worker-execution/score-worker-execution-impl/src/test/java/io/cloudslang/worker/execution/services/ExecutionServiceTest.java
Flows were stuck in running for RPA Activities if on production environments (Faster environments).
This was happening due to the order of execution steps. First the message/execution was produced on queue, and then it was paused.
This triggered a race condition in which if there was some sort of check on the execution between putting the message on the queue and pausing the execution, a null pointer was thrown.
What was done: reverted the order (pause -> execute), removed the set pause status from other places, changed how the doAction method works in Cloudslang such that the runEnvironment is fully populated before pausing (and persisting) the execution.
Also fixed another defect that made the Multi Instance with one lane having RPA activities fail because the branchId was mistakenly …
=> Flows were stuck in running for RPA Activities

engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/entities/WorkerKeepAliveInfo.java, engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/services/WorkerNodeService.java, engine/node/score-node-impl/src/main/java/io/cloudslang/engine/node/services/WorkerNodeServiceImpl.java, package/score-worker/src/main/java/io/cloudslang/schema/WorkerBeanDefinitionParser.java, worker/worker-manager/score-worker-manager-api/src/main/java/io/cloudslang/worker/management/monitor/WorkerStateUpdateService.java, worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/monitor/WorkerStateUpdateServiceImpl.java, worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/InBuffer.java, worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerManager.java, worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/monitor/ScheduledWorkerLoadMonitorTest.java, worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/monitor/WorkerMonitorsImplTest.java, worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/services/InBufferTest.java, worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/services/WorkerManagerTest.java
When worker is not enabled, it will not perform polling for messages.
=> Prevent polling when worker is not active

runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonExecutionEngineConfiguration.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonRuntimeServiceImpl.java, runtime-management/runtime-management-impl/src/test/java/io/cloudslang/runtime/impl/python/PythonExecutorTest.java
Limit concurrent python executions (+eval)
Configurable using 'python.concurrent.execution.permits' system property
Signed-off-by: Tirla Florin-Alin <tirla@microfocus.com>
=> Limit concurrent python executions (+eval)

package/score-worker/src/main/resources/META-INF/spring/score/context/scoreWorkerSchedulerContext.xml
Introduce system property `-Doutbuffer.drain.period=250` to be able to configure the the outbuffer draining period in miliseconds.
=> Outbuffer delay

engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/score/facade/execution/LicenseType.java
Added new license type for hourly fallback. It means that if no concurrent is available for the selected flow then run it with hourly .
Signed-off-by: Igor Vorobiov igor.vorobiov@microfocus.com
=> added CONCURRENT_HOURLY license type

worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
Make run execution interval configurable via system property `worker.executionIntervalSeconds`.
=> Make run execution interval configurable

runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutor.java, runtime-management/runtime-management-impl/src/main/resources/eval.py
lists having quotes inside elements were causing execution to fail because they couldn't be parsed: ["temp", "'tem,p'"]
Signed-off-by: Adriana Corui adriana-natalia.corui@microfocus.com
=> allow single quotes in deserialization

worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/OutboundBufferImpl.java, worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/services/OutboundBufferTest.java
Change the list to a hashmap to avoid grouping to have a a faster optimize of messages.
=> Outbuffer performance improvements

worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/OutboundBufferImpl.java, worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/services/OutboundBufferTest.java
Outbound buffer capacity is now configurable from system property `out.buffer.entries`, with default value taken from the number of execution threads.
=> Outbound buffer capacity

engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/services/WorkerNodeService.java, engine/node/score-node-impl/src/main/java/io/cloudslang/engine/node/services/WorkerNodeServiceImpl.java, engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/entities/MergedConfigurationDataContainer.java, engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/PauseResumeService.java, engine/orchestrator/score-orchestrator-impl/pom.xml, engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/model/MergedConfigurationHolder.java, engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/MergedConfigurationServiceImpl.java, engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/StubPauseResumeServiceImpl.java, engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/MergedConfigurationServiceTest.java, pom.xml
Optimized merged configuration by using a single orchestrator job instead of per worker job to update the merged configuration.
Refresh period can be controlled using `"worker.mergedConfiguration.refreshDelayMillis"` system property. Its default value is `1_800 miliseconds`.
=> Optimize merged configuration

runtime-management/runtime-management-api/src/main/java/io/cloudslang/runtime/api/python/ExternalPythonProcessRunService.java, runtime-management/runtime-management-impl/pom.xml, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutionEngine.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutorCompletableFutureTimeout.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutorScheduledExecutorTimeout.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutorWaitForTimeout.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonTestRunnable.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonTimeoutRunnable.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/model/TempEnvironment.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/model/TempEvalEnvironment.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/model/TempExecutionEnvironment.java
Adding 2 new timeout strategies, extracting old one as strategy
`-Dpython.timeoutStrategy=wait-for|scheduled-executor|completable-future`
This property is not present in score the default value if unspecified is `scheduled-executor`
First two strategies have a better execution performance than the `completable-future` strategy. 
=> python 3 timeout performance fix

runtime-management/runtime-management-impl/src/main/resources/eval.py
Use apostrophe instead of inverted comma
=> Fix eval for xpath

runtime-management/runtime-management-impl/src/main/resources/eval.py
Wrapped the result in str to avoid errors when it would be dumped as json. Some objects were not being recognised as json serializable (complex numbers, bytearrays). Such cases would result in an empty string instead of a json being printed
Signed-off-by: Radoi Teodor teodorandrei.radoi@microfocus.com
=> Avoid json dump errors

runtime-management/runtime-management-impl/src/main/resources/eval.py
HttpClientInputs Keystore and trustKeystore are initialized incorrectly when expression result is None. 
It causes failure for steps like http_client_action_get:
The trust keystore provided in the 'trustKeystore' input is corrupted OR the password (in the 'trustPassword' input) is incorrect
Signed-off-by: Igor Vorobiov igor.vorobiov@microfocus.com
=> Fixed case when str(expr_result) = None

pom.xml, runtime-management/runtime-management-impl/pom.xml, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/ExecutionCachedEngine.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/EmbeddedPythonExecutorWrapper.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonExecutionCachedEngine.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonExecutionEngine.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonExecutionEngineConfiguration.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonExecutionPooledAndCachedEngine.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonRuntimeServiceImpl.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/pool/ViburEmbeddedPythonFactory.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/pool/ViburEmbeddedPythonPoolService.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/pool/ViburEmbeddedPythonPoolServiceImpl.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/security/BoundStringWriter.java, runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/security/BoundedStringWriter.java
- do not use jython threadlocal locals inside engine threadpool, change of strategy
By default the argument passed for jython strategy is `-Dpython.executor.engine=PythonExecutionPooledAndCachedEngine`
- use dedicated pool for jython executors to handle jython content without dependencies 
- use dedicated cache for jython executors to handle jython content with dependencies 
- better security for jython standard streams handling
=> jython refactoring

worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
There are cases when executing a flow in debug mode and we get invalid (expression) worker group details.
In this case, we want the flow to ignore the worker group and execute flow normally.
=> Execute flow in debug mode even if worker group is not valid.

engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/entities/FinishedBranch.java, engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/entities/SuspendedExecution.java, engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/SplitJoinServiceImpl.java, engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/repositories/SuspendedExecutionsRepositoryTest.java, engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/SplitJoinServiceTest.java
If one of the branch would fail for parallel or multi instance flow, the entity would be saved in database. 
If the user would cancel the flow, all the branches would be saved in database even the previous branch that failed. That would result in an exception: unique key validation for branchId and splitId. 
Signed-off-by: Larisa Bratean <larisa-alexandra.bratean@microfocus.com>
=> check if branch exists already

worker/worker-monitor/score-worker-monitor-impl/src/main/java/io/cloudslang/worker/monitor/PerformanceMetricsCollector.java, worker/worker-monitor/score-worker-monitor-impl/src/main/java/io/cloudslang/worker/monitor/mbean/WorkerMetricsMBean.java
The RAS workers were crashing even after worker busyness feature is disabled.
=> Busyness feature disable NPE

engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/QueueListenerImpl.java, engine/queue/score-queue-impl/src/test/java/io/cloudslang/engine/queue/services/QueueListenerImplTest.java
Add safety check to not checkout license if the flow is canceled
In case the pause execution for no license gets executed after the pending cancel of the flow because of the job, ignore the pause of execution and dispatch the messages for pending cancel
=> add safety check before micro step and check pending license

engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/CancelExecutionServiceImpl.java, engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/CancelExecutionServiceTest.java, engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/QueueListenerImpl.java
- changed it so a flow should not pause if terminationType is set to CANCELED
- changed cancelPausedRun logic to terminate any branch that has an executionObject, and put the others on CANCELED
=> - fixed flows remaining stuck in pending cancel when a run was canceled while paused with no RAS

worker/worker-manager/score-worker-manager-api/src/main/java/io/cloudslang/worker/management/services/SynchronizationManager.java, worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/OutboundBufferImpl.java, worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SynchronizationManagerImpl.java
In case of spring closing, the notEmpty condition was still in await state resulting in delay in the shutdown of service.
To be able to fix it, we lock the ReentrantLock to be able to signal the notEmpty condition, and unlock it at the end.
=> Fix shutdown of service for locks

engine/orchestrator/score-orchestrator-api/pom.xml, engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/ExecutionCleanerService.java, engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/ExecutionStateService.java, engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/ExecutionCleanerServiceImpl.java, engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/ExecutionStateServiceImpl.java, engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/FinishedExecutionStateCleanerServiceImpl.java, engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/ExecutionStateServiceTest.java, engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/entities/ExecutionStatesData.java, engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepository.java, engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/services/cleaner/QueueCleanerService.java, engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryImpl.java, engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/cleaner/QueueCleanerServiceImpl.java, engine/queue/score-queue-impl/src/test/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryTest.java, engine/queue/score-queue-impl/src/test/java/io/cloudslang/engine/queue/services/cleaner/QueueCleanerServiceTest.java, engine/score-engine-jobs/src/main/java/io/cloudslang/job/ScoreEngineJobs.java, engine/score-engine-jobs/src/main/java/io/cloudslang/job/ScoreEngineJobsImpl.java, package/score-all/src/main/java/io/cloudslang/schema/EngineBeanDefinitionParser.java, package/score-all/src/main/resources/META-INF/spring/score/context/scoreEngineSchedulerContext.xml, worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExternalExecutionServiceImpl.java
- unifying QueueCleanerJob and FinishedExecutionStateCleanerJob into one single clean-up job 
- changed ExecutionStateServiceImpl#updateExecutionStateStatus and ExecutionStateServiceImpl#updateExecutionObject so updateTime is updated with each update to the ExecutionState entity
=> Enhance the engine queue cleanup mechanism
