CloudSlang/score

- pom.xml
Signed-off-by: Eliya Sadan eliyasadan@gmail.com
> update spring to 4.1.4

- README.md
- pom.xml
Changes required for automating release to Maven Central
> Adapt to Maven Central Releases

- package/score-worker/src/main/java/org/openscore/schema/WorkerBeanDefinitionParser.java
- package/score-worker/src/main/resources/META-INF/spring/score/context/scoreWorkerSchedulerContext.xml
- score-api/src/main/java/org/openscore/events/EventConstants.java
- worker/worker-manager/score-worker-manager-api/src/main/java/org/openscore/worker/management/monitor/ScheduledWorkerMonitor.java
- worker/worker-manager/score-worker-manager-api/src/main/java/org/openscore/worker/management/monitor/WorkerMonitor.java
- worker/worker-manager/score-worker-manager-api/src/main/java/org/openscore/worker/management/monitor/WorkerMonitors.java
- worker/worker-manager/score-worker-manager-api/src/main/java/org/openscore/worker/management/services/WorkerExecutionMonitorService.java
- worker/worker-manager/score-worker-manager-api/src/main/java/org/openscore/worker/management/services/WorkerMonitorInfoEnum.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/org/openscore/worker/management/monitor/ScheduledWorkerLoadMonitor.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/org/openscore/worker/management/monitor/WorkerMonitorsImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/org/openscore/worker/management/services/InBuffer.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/org/openscore/worker/management/services/WorkerExecutionMonitorServiceImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/org/openscore/worker/management/services/WorkerManager.java
- worker/worker-manager/score-worker-manager-impl/src/test/java/org/openscore/worker/management/monitor/ScheduledWorkerLoadMonitorTest.java
- worker/worker-manager/score-worker-manager-impl/src/test/java/org/openscore/worker/management/monitor/WorkerMonitorsImplTest.java
- worker/worker-manager/score-worker-manager-impl/src/test/java/org/openscore/worker/management/services/WorkerExecutionMonitorServiceImplTest.java
Signed-off-by: Genadi Rabinovich <genadi@hp.com>
@orius123 please review
> worker status monitoring - first draft

- score-api/src/main/java/org/openscore/events/EventBus.java
Signed-off-by: Sam Markowitz <sam.markowitz@hp.com>
> fixed typo and readability

- engine/queue/score-queue-api/src/main/java/org/openscore/engine/queue/services/QueueListener.java
- engine/queue/score-queue-impl/src/main/java/org/openscore/engine/queue/services/ExecutionQueueServiceImpl.java
- engine/queue/score-queue-impl/src/main/java/org/openscore/engine/queue/services/QueueListenerImpl.java
- engine/queue/score-queue-impl/src/main/java/org/openscore/engine/queue/services/statistics/WorkerQueueStatisticsImpl.java
Signed-off-by: Eliya Sadan <eliyasadan@gmail.com>
> added pre persist method to queue listener and to implementations

- CONTRIBUTING.md
Fixes #14
Signed-off-by: Sam Markowitz <sam.markowitz@hp.com>
> strengthened test requirements

- CONTRIBUTING.md
- README.md
Signed-off-by: Sam Markowitz <sam.markowitz@hp.com>
> docs changes for rename

- package/score-all/src/main/resources/META-INF/spring/score/context/scoreRepositoryContext.xml
Signed-off-by: Meir Wahnon <meir.wahnon@hp.com>
> remove unneeded xml scheme location

- package/score-all/src/main/java/io/cloudslang/schema/context/ScoreDefaultDatasourceContext.java
> change default db name

- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
Signed-off-by: Natasha Beck natasha.beck@hp.com
> shared JDBC issue - causes inconsistent behaviour

- worker/worker-manager/score-worker-manager-api/src/main/java/io/cloudslang/worker/management/ExecutionsActivityListener.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/InBuffer.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/OutboundBufferImpl.java
@shajyhia does it fit for your requirements?
@meirwah @oritstone @natabeck WDYT?
> Worker Poll / Dispatch listener

- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/CancelExecutionServiceImpl.java
- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/QueueListenerImpl.java
> delete branches in execution state table when trying to cancel pause

- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
Signed-off-by: Bonczidai Levente <levente.bonczidai@hp.com>
> OOM issue: remove redundant data from system context for branches

- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryImpl.java
Fix deadlock issue on MSSQL, where Tx1 (enqueue) locks table S and then tries to lock Q, while Tx2 (cleanup) locks table Q and then tries to lock S - so both are waiting for each other to end. Aligning the table access order between the two transactions prevents the deadlock condition.
> Fix deadlock issue on MSSQL

- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryImpl.java
Fix deadlock issue on MSSQL, where Tx1 (enqueue) locks table S and then Q, while Tx2 (cleanup) locks table Q and then S - so both are waiting for each other to end. Aligning the table access order between the two transactions prevents the deadlock condition. (commit: 43dd239765c823c486f572935e95a788baa0f759) — rotem.eisenthal
Signed-off-by: Meir Wahnon <meir.wahnon@hp.com>
> merging fix :

- engine/data/score-data-api/pom.xml
- engine/data/score-data-api/src/main/java/io/cloudslang/engine/dialects/ScoreDialectResolver.java
- engine/orchestrator/score-orchestrator-impl/pom.xml
- pom.xml
Signed-off-by: Yoel Lerner <yoel.lerner@hp.com>
> use spring-io platform third party recommendations

- package/score-worker/src/main/java/io/cloudslang/schema/WorkerBeanDefinitionParser.java
- package/score-worker/src/main/resources/META-INF/spring/score/context/scoreWorkerSchedulerContext.xml
- pom.xml
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerManager.java
cancel execution by interrupting its thread
> Cancel execution by timeout

- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/CancelExecutionServiceImpl.java
- engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/CancelExecutionServiceTest.java
merged from score-0.2.2
Signed-off-by: Hajyhia Shehab shehab.hajyhia@hpe.com
>  support  Interrupt execution in pending-status

- engine/data/score-data-api/src/main/resources/META-INF/database/score.changes.xml
- engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/entities/Worker.java
- engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/entities/WorkerNode.java
- engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/services/WorkerNodeService.java
- engine/node/score-node-impl/src/main/java/io/cloudslang/engine/node/services/WorkerNodeServiceImpl.java
- engine/node/score-node-impl/src/test/java/io/cloudslang/engine/node/services/WorkerNodeServiceTest.java
- score-tests/src/test/java/io/cloudslang/schema/EngineTest.java
- worker/worker-manager/score-worker-manager-api/src/main/java/io/cloudslang/worker/management/services/WorkerVersionService.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerManager.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerRecoveryManagerImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerVersionServiceImpl.java
- worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/services/WorkerManagerTest.java
Version ID is a comparable String
> Add to worker the ability to report its version ID

- engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/entities/ExecutionMessageConverter.java
- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/QueueDispatcherServiceImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerManager.java
- worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/monitor/ScheduledWorkerLoadMonitorTest.java
- worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/monitor/WorkerMonitorsImplTest.java
- worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/services/WorkerManagerTest.java
Prevent worker to start activity if its version does not match engine's
> Adaptive ras branch

- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
small bug was found in the previous pull request... fixing it
> Add stepPersist capability to the engine

- engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/entities/WorkerNode.java
- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/QueueListenerImpl.java
- score-samples/hello-score/src/main/java/io/cloudslang/samples/HelloScore.java
fixes #88 
Signed-off-by: Bonczidai Levente <levente.bonczidai@hp.com>
> Security fixes

- engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/entities/MergedConfigurationDataContainer.java
- engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/MergedConfigurationService.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/MergedConfigurationServiceImpl.java
- engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/MergedConfigurationServiceTest.java
- package/score-all/src/main/java/io/cloudslang/schema/EngineBeanDefinitionParser.java
- score-tests/src/test/java/io/cloudslang/schema/WorkerTest.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/WorkerConfigurationServiceImpl.java
Added a merged configuration service which merges the requests for:
1. paused flows
2. cancelled flows
3. worker groups
to a single service request
Signed-off-by: Doron Sekler <doron.sekler@hpe.com>
> Added MergedConfigurationService

- dependency-management/dependency-management-impl/src/main/java/io/cloudslang/dependency/impl/services/DependencyServiceImpl.java
- runtime-management/runtime-management-impl/pom.xml
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/ExecutionCachedEngine.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/java/JavaExecutor.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonExecutor.java
1. Under some circumstances leaks of python interpreters and java classloaders can occur. 
2. Jython modules management is not stable under multithreaded stress test: modules which are exist eventually not found (for some reason). We solve this with retry and will open an issue for Jytho.org
Sign-off: @genadi-hp, Genadi Rabinovich, genadi@hpe.com
> Urgent bug fixes for Java / Python execution with versioning

- dependency-management/dependency-management-api/src/main/java/io/cloudslang/dependency/api/services/MavenConfig.java
- dependency-management/dependency-management-impl/pom.xml
- dependency-management/dependency-management-impl/src/main/java/io/cloudslang/dependency/impl/services/DependencyServiceImpl.java
- dependency-management/dependency-management-impl/src/main/java/io/cloudslang/dependency/impl/services/utils/UnzipUtil.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/java/JavaExecutor.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonExecutor.java
- score-api/src/main/java/io/cloudslang/score/api/ScoreDeprecated.java
Sign-off: @genadi-hp, Genadi Rabinovich, genadi@hpe.com
> Added log file dedicated to maven executions (per GAV)

- score-api/src/main/java/io/cloudslang/score/api/execution/ExecutionParametersConsts.java
- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
Sign-off:@genadi-hp, Genadi Rabinovich, genadi@hpe.com
> Introduce constant for child branches which will be consumed in more classes

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonExecutor.java
- runtime-management/runtime-management-impl/src/test/java/io/cloudslang/runtime/impl/python/PythonExecutorTest.java
> exclude pyclass from python executor result context

- engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/MergedConfigurationService.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/MergedConfigurationServiceImpl.java
- engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/MergedConfigurationServiceTest.java
- engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/services/BusyWorkersService.java
- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/BusyWorkersServiceImpl.java
- package/score-all/src/main/resources/META-INF/spring/score/context/scoreEngineSchedulerContext.xml
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/WorkerConfigurationServiceImpl.java
Keeping busy workers for 5000ms
worker will send worker id in mergedConfigurationService
Signed-off-by: Doron Sekler doron.sekler@hpe.com
> Keeping busy workers for 5000ms;worker will send worker id in mergedConfigurationService

- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/RunningExecutionPlanServiceImpl.java
- engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/RunningExecutionPlanServiceTest.java
- score-api/src/main/java/io/cloudslang/score/api/ExecutionPlan.java
Signed-off-by: Lerner Yoel <yoel.lerner@hpe.com>
> change the timestamp to UUID related to my first change

- dependency-management/dependency-management-impl/src/test/java/io.cloudslang.dependency.impl.services/DependencyServiceTest.java
> Fix maven build failure

- pom.xml
> Downgrade hibernate

- dependency-management/dependency-management-impl/src/main/java/io/cloudslang/dependency/impl/services/MavenConfigImpl.java
- engine/node/score-node-impl/src/test/java/io/cloudslang/engine/node/services/WorkerNodeServiceTest.java
- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryImpl.java
- runtime-management/runtime-management-impl/src/test/java/io/cloudslang/runtime/impl/python/PythonExecutorTest.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/SessionDataHandlerImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/InBuffer.java
> resolve code climate issues

- score-samples/hello-score/src/main/java/io/cloudslang/samples/HelloScore.java
- score-samples/hello-score/src/main/resources/log4j.properties
> Small updates - make Hello Score work

- dependency-management/dependency-management-impl/pom.xml
- dependency-management/dependency-management-impl/src/main/java/io/cloudslang/dependency/impl/services/DependencyServiceImpl.java
- dependency-management/dependency-management-impl/src/test/java/io.cloudslang.dependency.impl.services/DependencyServiceTest.java
- runtime-management/runtime-management-impl/src/test/java/io/cloudslang/runtime/impl/python/PythonExecutorTest.java
- score-api/src/main/java/io/cloudslang/score/events/EventConstants.java
Related to https://github.com/CloudSlang/cloud-slang/issues/846
Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com
> Downloading artifact message

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/constants/ScoreContentSdk.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/java/JavaExecutor.java
- runtime-management/runtime-management-impl/src/test/java/io/cloudslang/runtime/impl/java/JavaExecutorTest.java
related to https://github.com/CloudSlang/cloud-slang/issues/959
closes #133 
> Classpath isolation bugfix

- engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/services/WorkerNodeService.java
- engine/node/score-node-impl/src/main/java/io/cloudslang/engine/node/services/WorkerNodeServiceImpl.java
- engine/node/score-node-impl/src/test/java/io/cloudslang/engine/node/services/WorkerNodeServiceTest.java
This PR contains a new feature: restore a deleted worker.
Signed-off-by: Tirla Florin-Alin <tirla@hpe.com>
> Feature: Restore deleted worker

- engine/node/score-node-api/src/main/java/io/cloudslang/engine/node/services/WorkerNodeService.java
> Fixed typo

- engine/node/score-node-impl/src/main/java/io/cloudslang/engine/node/repositories/WorkerNodeRepository.java
Signed-off-by: Levente Bonczidai <levente.bonczidai@hpe.com>
> fix oracle db query

- dependency-management/pom.xml
- pom.xml
- runtime-management/pom.xml
Signed-off-by: Levente Bonczidai <levente.bonczidai@hpe.com>
> Spring IO Upgrades

- engine/data/score-data-api/src/main/java/io/cloudslang/engine/data/AbstractIdentifiable.java
- engine/data/score-data-api/src/main/java/io/cloudslang/engine/data/Identifiable.java
- engine/data/score-data-api/src/main/java/io/cloudslang/engine/partitions/entities/PartitionGroup.java
- engine/data/score-data-api/src/main/java/io/cloudslang/engine/partitions/services/PartitionService.java
- engine/data/score-data-api/src/main/java/io/cloudslang/engine/partitions/services/PartitionTemplate.java
- engine/data/score-data-impl/src/main/java/io/cloudslang/engine/partitions/repositories/PartitionGroupRepository.java
- engine/data/score-data-impl/src/main/java/io/cloudslang/engine/partitions/services/PartitionServiceImpl.java
- engine/data/score-data-impl/src/main/java/io/cloudslang/engine/partitions/services/PartitionTemplateImpl.java
- engine/data/score-data-impl/src/main/java/io/cloudslang/engine/partitions/services/PartitionUtils.java
- engine/data/score-data-impl/src/test/java/io/cloudslang/engine/partitions/services/PartitionServiceTest.java
- engine/data/score-data-impl/src/test/java/io/cloudslang/engine/partitions/services/PartitionTemplateTest.java
- engine/data/score-data-impl/src/test/java/io/cloudslang/engine/partitions/services/PartitionTemplateWithEmfTest.java
- engine/node/score-node-impl/src/main/java/io/cloudslang/engine/node/services/WorkerNodeServiceImpl.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/OrchestratorDispatcherServiceImpl.java
- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/callbacks/AbstractCallback.java
- engine/score-facade/src/main/java/io/cloudslang/score/facade/entities/Execution.java
- package/score-all/src/main/java/io/cloudslang/schema/EngineBeanDefinitionParser.java
- package/score-worker/src/main/java/io/cloudslang/schema/BeanRegistrator.java
- package/score-worker/src/main/java/io/cloudslang/schema/ScoreNamespaceHandler.java
- package/score-worker/src/main/java/io/cloudslang/schema/WorkerBeanDefinitionParser.java
- pom.xml
- score-api/src/main/java/io/cloudslang/score/api/ExecutionPlan.java
- score-api/src/main/java/io/cloudslang/score/api/ExecutionStep.java
- score-tests/src/test/java/io/cloudslang/schema/EngineTest.java
- score-tests/src/test/java/io/cloudslang/schema/WorkerTest.java
- worker/worker-execution/score-worker-execution-api/src/main/java/io/cloudslang/worker/execution/services/ExecutionService.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/RetryTemplate.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerRecoveryManagerImpl.java
Removed empty authors
deactivated doclint for maven-javadoc-plugin
Signed-off-by: Victor Ursan <victor.ursan@hpe.com>
> Fixed some javadoc errors

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/java/JavaExecutor.java
Signed-off-by: Victor Ursan <victor.ursan@hpe.com>
> Added getParentClassLoader method in JavaExecutor in order to obtain the Class loader of the SDK

- .codeclimate.yml
- .travis.yml
- README.md
Added Sonar JAVA
Added test coverage
Added checkstyle
Signed-off-by: moldovso <sorin@hpe.com>
> Add codeclimate support

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonExecutor.java
Signed-off-by: Levente Bonczidai <levente.bonczidai@hpe.com>
> Python context filtering

- engine/data/score-data-api/src/main/resources/META-INF/database/score.changes.xml
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/repositories/RunningExecutionPlanRepository.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/RunningExecutionPlanServiceImpl.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/ScoreTriggeringImpl.java
- engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/RunningExecutionPlanServiceTest.java
- engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/ScoreTriggeringTest.java
- engine/score-facade/src/main/java/io/cloudslang/score/facade/entities/RunningExecutionPlan.java
- engine/score-facade/src/main/java/io/cloudslang/score/facade/services/RunningExecutionPlanService.java
- pom.xml
added run id for  the execution plan 
Problem solved: when running execution plans are persisted the table can become quite big, so get is not efficient and could lead to out of memory issues.
Second  commit is for updating libraries for vulnerabilities
> Running exec plans

- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/repositories/RunningExecutionPlanRepository.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/RunningExecutionPlanServiceImpl.java
- engine/score-facade/src/main/java/io/cloudslang/score/facade/services/RunningExecutionPlanService.java
return total number of deleted items
> 35056 fix for delete execution plans

- engine/data/score-data-api/src/main/java/io/cloudslang/engine/data/SimpleHiloIdentifierGenerator.java
- pom.xml
migrating hibernate to 5.2.17.final
> Hibernate upgrade

- pom.xml
Signed-off-by: nitoiu <cristian.nitoiu@hpe.com>
> CVE-2016-3720 upgrade jackson-annotations

- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/BusyWorkersServiceImpl.java
> Fix polling

- engine/score-facade/src/main/java/io/cloudslang/score/facade/TempConstants.java
- pom.xml
- worker/worker-execution/score-worker-execution-impl/pom.xml
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/model/SandboxExecutionRunnable.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
- worker/worker-execution/score-worker-execution-impl/src/test/java/io/cloudslang/worker/execution/services/ExecutionServiceTest.java
Improve timeout for score by providing a platform level operation execution timeout.
> Timeout changes for score

- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerManager.java
> Configure future cancellation based on a system property

- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/InBuffer.java
> Fix issue with capacity when in other mode

- engine/orchestrator/score-orchestrator-impl/pom.xml
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/OrchestratorDispatcherServiceImpl.java
- pom.xml
> Remove library

- worker/worker-execution/score-worker-execution-impl/src/test/java/io/cloudslang/worker/execution/services/ExecutionServiceTest.java
Signed-off-by: cimpeanr <radu.cimpean@microfocus.com>
> test that reaching sequential operation pauses the execution

- engine/queue/score-queue-api/pom.xml
- engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/entities/ExecutionMessageConverter.java
- engine/queue/score-queue-api/src/test/java/io/cloudslang/engine/queue/entities/ExecutionMessageConverterTest.java
> Gzip ExecutionMessage

- engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/entities/MergedConfigurationDataContainer.java
- engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/MergedConfigurationService.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/CancelExecutionServiceImpl.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/MergedConfigurationServiceImpl.java
- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
- worker/worker-manager/score-worker-manager-api/src/main/java/io/cloudslang/worker/management/WorkerConfigurationService.java
- worker/worker-manager/score-worker-manager-api/src/main/java/io/cloudslang/worker/management/services/EndExecutionCallback.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/WorkerConfigurationServiceImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerManager.java
- worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/services/SimpleExecutionRunnableTest.java
> Code quality fixes

- pom.xml
> Upgraded jackson databind

- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
> Minor performance improvements

- pom.xml
- worker/worker-manager/score-worker-manager-impl/pom.xml
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerConfigurationUtils.java
> Remove disruptor

- score-tests/src/test/java/io/cloudslang/schema/EngineTest.java
- worker/worker-execution/score-worker-execution-api/src/main/java/io/cloudslang/worker/execution/services/ExecutionService.java
- worker/worker-execution/score-worker-execution-api/src/main/java/io/cloudslang/worker/execution/services/ExternalExecutionService.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExternalExecutionServiceImpl.java
Signed-off-by: gituser173 <claudiu-laurian.ban@hpe.com>
> refactoring

- engine/queue/score-queue-api/pom.xml
- engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/entities/ExecutionMessageConverter.java
- pom.xml
> Lz4 for Execution Messages

- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/WorkerManager.java
> Less contention because of faster code in synchronized block.

- package/score-worker/src/main/java/io/cloudslang/schema/WorkerBeanDefinitionParser.java
- worker/worker-manager/score-worker-manager-api/src/main/java/io/cloudslang/worker/management/services/SimpleRunnableContinuation.java
- worker/worker-manager/score-worker-manager-impl/pom.xml
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/delegate/ContinuationOutbufferInbufferRunnable.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/delegate/ContinuationOutbufferRunnable.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnableFactory.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleRunnableContinuationDelegate.java
- worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/monitor/WorkerMonitorsImplTest.java
- worker/worker-manager/score-worker-manager-impl/src/test/java/io/cloudslang/worker/management/services/SimpleExecutionRunnableTest.java
> Fixing contention of score threads during outbuffer put operation.

- engine/score-facade/src/main/java/io/cloudslang/score/facade/entities/Execution.java
- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
+ fix faulty worker group logic
> support for worker groups event

- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
Sequential execution details
Signed-off-by: Tirla Florin-Alin <tirla@microfocus.com>
> Sequential execution details

- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/repositories/SuspendedExecutionsRepository.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/SuspendedExecutionCleanerServiceImpl.java
Added explicit coversion to suspended execution repository
> Explicit conversion

- .travis.yml
Fix travis; jdk 11 not yet supported
Signed-off-by: Tirla Florin-Alin <tirla@microfocus.com>
> Fix travis; jdk 11 not yet supported

- engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/services/LargeMessagesMonitorService.java
> Changing to 24 retries

- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/LargeMessagesMonitorServiceImpl.java
> Fixing large message job

- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryImpl.java
fix disable flag for legacy query
> added large query for mysql

- engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/entities/ExecutionMessage.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/OutboundBufferImpl.java
- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
> Minor optimizations

- engine/orchestrator/score-orchestrator-impl/pom.xml
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/ExecutionSerializationUtil.java
- engine/queue/score-queue-api/pom.xml
- engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/entities/ExecutionMessageConverter.java
- engine/score-facade/pom.xml
- engine/score-facade/src/main/java/io/cloudslang/score/facade/entities/ExecutionPlanCompressUtil.java
- pom.xml
> Adding FastByteArrayOutputStream

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutor.java
> Revert "Fixed big inputs issue."

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutor.java
> Fixed big inputs and timeout

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutor.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ScriptResults.java
- runtime-management/runtime-management-impl/src/main/resources/main.py
* Create traceback list from python and send it together with the exception.
* Parse the traceback list and get the last element.
* Create traceback list from python exc_tb parsed with a special function borrowed from python, but modified.
> Show line number for python script error

- engine/orchestrator/score-orchestrator-impl/pom.xml
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/ExecutionSerializationUtil.java
- engine/queue/score-queue-api/pom.xml
- engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/entities/ExecutionMessageConverter.java
- engine/score-facade/pom.xml
- engine/score-facade/src/main/java/io/cloudslang/score/facade/entities/ExecutionPlanCompressUtil.java
- pom.xml
> Remove fastutil

- pom.xml
> Promote lz4

- engine/score-facade/src/main/java/io/cloudslang/score/facade/entities/RunningExecutionPlan.java
> execution plan should be transient

- score-api/src/main/java/io/cloudslang/score/api/ExecutionStep.java
- worker/worker-execution/score-worker-execution-api/src/main/java/io/cloudslang/worker/execution/model/StepActionDataHolder.java
- worker/worker-execution/score-worker-execution-api/src/main/java/io/cloudslang/worker/execution/reflection/ReflectionAdapter.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/reflection/ReflectionAdapterImpl.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/SessionDataHandlerImpl.java
- worker/worker-execution/score-worker-execution-impl/src/test/java/io/cloudslang/worker/execution/reflection/ReflectionAdapterTest.java
- worker/worker-execution/score-worker-execution-impl/src/test/java/io/cloudslang/worker/execution/services/ExecutionServiceTest.java
Refactor the score engine loop.
Use less memory inside the loop.
Cleaning up the code.
> Refactor score engine loop

- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/SplitJoinServiceImpl.java
Set worker group on execution messages for cs parallel loop at split time.
Signed-off-by: Adriana Corui adriana-natalia.corui@microfocus.com
> worker groups handling for parallel loop

- .gitattributes
Adding git attributes file for this repository.
> Adding git attributes file

- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
Language pause to prevent spinning in case of internal engine pause
> language pause

- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryImpl.java
- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/LargeMessagesMonitorServiceImpl.java
- engine/queue/score-queue-impl/src/test/java/io/cloudslang/engine/queue/repositories/ExecutionQueueRepositoryTest.java
- engine/queue/score-queue-impl/src/test/java/io/cloudslang/engine/queue/services/LargeMessageMonitorServiceTest.java
> fix querying for large messages

- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/SplitJoinServiceImpl.java
- engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/services/SplitJoinServiceTest.java
- package/score-worker/src/main/java/io/cloudslang/schema/WorkerBeanDefinitionParser.java
- score-api/src/main/java/io/cloudslang/score/events/FastEventBus.java
- score-api/src/main/java/io/cloudslang/score/events/FastEventBusImpl.java
- score-api/src/main/java/io/cloudslang/score/events/UninterruptibleScoreEventListener.java
- score-tests/src/test/java/io/cloudslang/schema/EngineTest.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
- worker/worker-execution/score-worker-execution-impl/src/test/java/io/cloudslang/worker/execution/services/ExecutionServiceTest.java
Added fast event bus that is used for branch events.
Signed-off-by: Igor Vorobiov igor.vorobiov@microfocus.com
> Added fast eventbus

- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/ScoreEventFactoryImpl.java
- score-api/src/main/java/io/cloudslang/score/events/EventConstants.java
Signed-off-by: pinteae <eugen.pintea@microfocus.com>
> Add runEnv information on events

- engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/PauseResumeService.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/StubPauseResumeServiceImpl.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
Add methods for delete and create pause for no robots in group
Signed-off-by: Larisa Bratean <larisa-alexandra.bratean@microfocus.com>
> add methods for create and delete pause data for no robots in group

- engine/queue/score-queue-api/src/main/java/io/cloudslang/engine/queue/entities/ExecutionMessage.java
Fix ClassCastException io.cloudslang.orchestrator.entities.SplitMessage cannot be cast to io.cloudslang.engine.queue.entities.ExecutionMessage
> Fix ClassCastException

- engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/PauseResumeService.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/StubPauseResumeServiceImpl.java
- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
updated pause resume service for debugger support
> debugger breakpoints

- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
> Minor optimziation

- score-api/src/main/java/io/cloudslang/score/events/EventConstants.java
Added new event types for branches: SCORE_RESUMED_BRANCH_EVENT and SCORE_PAUSED_BRANCH_EVENT.
Signed-off-by: Denys Hryvastov denys.hryvastov@microfocus.com
> Added PAUSED and RESUMED events for branches.

- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
Needed for the actual computation done in cloud-slang
> Compute ROI value for parallel loops

- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/InBuffer.java
Fix for issue 
https://internal.almoctane.com/ui/entity-navigation?p=97002/7001&entityType=work_item&id=1175006
> Adding sleep to avoid continuous looping when worker is disabled

- runtime-management/runtime-management-impl/src/main/resources/eval.py
returning all results not only the first one
> return all results for cs_xpath_query

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutorCompletableFutureTimeout.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutorScheduledExecutorTimeout.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ResourceScriptResolver.java
- runtime-management/runtime-management-impl/src/main/resources/eval.py
Remove file system access from Python eval and test functionalities to improve performance.
> Python evaluation performance improvements

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutorScheduledExecutorTimeout.java
Signed-off-by: Alexandra Ilas alexandra.ilas@microfocus.com
> Changed int to bigint

- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
Add switch mode key on context.
Signed-off-by: Adriana Corui adriana-natalia.corui@microfocus.com
> execution key for switch mode

- engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/AplsLicensingService.java
Added new interface for UI steps concurrent license increment/decrement.
Signed-off-by: Denys Hryvastov denys.hryvastov@microfocus.com
> Rpa UI steps concurrent license increment/decrement

- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/InBuffer.java
Sleep longer and more carefully
> Inbuffer fix

- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/repositories/FinishedBranchRepository.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/repositories/SuspendedExecutionsRepository.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/SuspendedExecutionCleanerServiceImpl.java
- engine/orchestrator/score-orchestrator-impl/src/test/java/io/cloudslang/orchestrator/repositories/SuspendedExecutionsRepositoryTest.java
delete finished suspended execution entries and branches by number of finished branches
removed no longer used repository methods
> Defect 815490

- runtime-management/runtime-management-impl/src/main/resources/eval.py
Adding support for retrieving dynamic system properties i.e., get_sp_var("flow_input") where 'flow_input' is an input to a flow and returns the defined system property based on user input(i.e., flow_input)
> Adding support for retrieving dynamic system properties

- worker/worker-manager/score-worker-manager-impl/src/main/java/io/cloudslang/worker/management/services/SimpleExecutionRunnable.java
CPE : 1439916 | Studio Remote Debugger override RAS Not Working
> CPE : 1439916 | Studio Remote Debugger override RAS Not Working

- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
https://internal.almoctane.com/ui/entity-navigation?p=97002/7001&entityType=work_item&id=1499295
> add a new param into Execution Runtime Service

- engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/PauseResumeService.java
- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/StubPauseResumeServiceImpl.java
- engine/queue/score-queue-impl/src/main/java/io/cloudslang/engine/queue/services/QueueListenerImpl.java
- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
- worker/worker-execution/score-worker-execution-impl/src/test/java/io/cloudslang/worker/execution/services/ExecutionServiceTest.java
context for parent is not saved sometimes when no workers in group
> Check boolean for updating parent execution no workers

- dependency-management/dependency-management-impl/src/main/java/io/cloudslang/dependency/impl/services/DependencyServiceImpl.java
This reverts commit 9ac0a5b099998ac596b9f94655fcf473d90dc735.
> Revert "Add features for external injection (#442)"

- package/score-worker/src/main/java/io/cloudslang/schema/WorkerBeanDefinitionParser.java
- runtime-management/runtime-management-api/src/main/java/io/cloudslang/runtime/api/python/PythonExecutorConfigurationDataService.java
- runtime-management/runtime-management-api/src/main/java/io/cloudslang/runtime/api/python/entities/PythonExecutorDetails.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutorServiceImpl.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/StubPythonExecutorConfigurationDataServiceImpl.java
- runtime-management/runtime-management-impl/src/main/resources/pythonServer.properties
- score-api/src/main/resources/io/cloudslang/schema/score.xsd
Added a service a read from python executor configuration file
> Use python configuration file

- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
Enhancement of defect **OCTCR19F1452387.**
**Info :** This will allow customer to set overrideNRAS and overrideJRAS property from studio remote debugging.
> 1753456 | [Defect] Issue with OO studio debugger

- runtime-management/runtime-management-api/pom.xml
- runtime-management/runtime-management-api/src/main/java/io/cloudslang/runtime/api/python/PythonExecutorCommunicationService.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/PythonExecutionEngineConfiguration.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/executor/ExternalPythonExecutorServiceImpl.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/executor/PythonExecutorCommunicationServiceImpl.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/executor/PythonExecutorLifecycleManagerServiceImpl.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonScriptException.java
- runtime-management/runtime-management-impl/src/test/java/io/cloudslang/runtime/impl/python/PythonExecutorTest.java
Add PythonExecutorCommunicationService
> Refactor code for Python Executor

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/executor/PythonExecutorLifecycleManagerServiceImpl.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/PythonExecutorLifecycleManagerServiceImpl.java
Save in memory python executor status
> Added check for python executor process

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/executor/ExternalPythonExecutorServiceImpl.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/executor/PythonExecutorCommunicationServiceImpl.java
- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/executor/PythonExecutorLifecycleManagerServiceImpl.java
https://internal.almoctane.com/ui/entity-navigation?p=97002/7001&entityType=work_item&id=1818277
> Handle exception for missing python configuration

- worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
Verify property used only for studio local debugger
> revert part of a change to remove the worker group when studio local debug

- score-api/src/main/java/io/cloudslang/score/lang/ExecutionRuntimeServices.java
Changes aligned with respect to https://github.com/CloudSlang/cloud-slang/pull/1431
> CloudSlang Prompts should no longer pop-up to end-users for inputs with value

- runtime-management/runtime-management-impl/src/main/java/io/cloudslang/runtime/impl/python/external/ExternalPythonExecutorScheduledExecutorTimeout.java
- runtime-management/runtime-management-impl/src/main/resources/main.py
Fix Python execution for Qualys XML data that contains special characters which were not allowed until now
> Fix Python execution for Qualys XML data with special characters

- engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/score/facade/execution/LicenseType.java
Add Node license to the list of license types
> Add Node license type

- pom.xml
Upgraded spring to 3.3.2 Spring data jpa and 6.1.11
> Upgrade spring to latest

- engine/orchestrator/score-orchestrator-impl/src/main/java/io/cloudslang/orchestrator/services/SplitJoinServiceImpl.java
change the default from 12h to 24h
> change the default from 12h to 24h
